routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/login', 'Auth\LoginController@login');
Auth::routes();

//Admin Route
Route::group(['prefix' => 'mediuswareadmin', 'middleware' => 'auth'], function(){
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    //services
    Route::resource('services', 'Admin\ServicesController');
    Route::post('service/sortable', 'Admin\ServicesController@sortable');
    //category
    Route::resource('category', 'Admin\CategoryController');
    //portfolio
    Route::resource('portfolio', 'Admin\PortfolioController');
    Route::post('portfolio/sortable', 'Admin\PortfolioController@sortable');
    Route::get('portfolio/image/{id}/delete', 'Admin\PortfolioController@portfolioImageDelete');
    //team
    Route::resource('team', 'Admin\TeamController');
    Route::post('team/sortable', 'Admin\TeamController@sortable');
    //slider
    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/sortable', 'Admin\SliderController@sortable');
    //feature
    Route::resource('feature', 'Admin\FeatureController');
    //setting
    Route::get('setting', 'Admin\DashboardController@setting');
    Route::post('setting/store', 'Admin\DashboardController@settingStore');
    //career
    Route::resource('careers', 'Admin\CareerController');
    //contact
    Route::get('contacts', 'Admin\DashboardController@contacts');
    Route::get('contact/delete/{id}', 'Admin\DashboardController@contactDelete');
    //about
    Route::resource('about', 'Admin\AboutController');
    Route::post('about/sortable', 'Admin\AboutController@sortable');
    //technology
    Route::resource('technology', 'Admin\TechnologyController');
    Route::post('technology/sortable', 'Admin\TechnologyController@sortable');
    //client
    Route::resource('client', 'Admin\ClientController');
    Route::post('client/sortable', 'Admin\ClientController@sortable');
    //client
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('partner/sortable', 'Admin\PartnerController@sortable');
    //informative
    Route::resource('informative-text', 'Admin\InformativeTextController');
    //informative
    Route::resource('testimonial', 'Admin\TestimonialController');


    Route::group(['middleware' => 'admin'], function(){
        //user
        Route::resource('user', 'Admin\UserController');
        Route::post('user/sortable', 'Admin\UserController@sortable');
    });

});

//Frontend Route
Route::get('/get-abouts', 'WebsiteController@getAbouts');
Route::get('/get-portfolios-showcase', 'WebsiteController@getPortfolioShowcase');
Route::get('/get-portfolios', 'WebsiteController@getPortfolios');
Route::get('/get-portfolios/{slug}', 'WebsiteController@getPortfolios');
Route::get('/get-portfolio-details/{slug}', 'WebsiteController@getPortfolioDetails');
Route::get('/get-categories', 'WebsiteController@getCategories');
Route::get('/get-features', 'WebsiteController@getFeatures');
Route::get('/get-feature-details/{slug}', 'WebsiteController@getFeatureDetails');
Route::get('/get-services', 'WebsiteController@getServices');
Route::get('/get-service-details/{slug}', 'WebsiteController@getServiceDetails');
Route::get('/get-setting', 'WebsiteController@getSettingInfo');
Route::get('/get-teams', 'WebsiteController@getTeam');
Route::get('/get-team-details/{slug}', 'WebsiteController@getTeamDetails');
Route::post('/contact-store', 'WebsiteController@contactStore');
Route::post('/team-contact-store', 'WebsiteController@teamContactStore');
Route::post('/newsletter-store', 'WebsiteController@newsletterStore');
Route::get('/get-technology', 'WebsiteController@getTechnology');
Route::get('/get-clients', 'WebsiteController@getClients');
Route::get('/get-sliders', 'WebsiteController@getSliders');
Route::get('/get-informative-text', 'WebsiteController@getInformativeText');
Route::get('/get-testimonials', 'WebsiteController@getTestimonials');
Route::get('/get-partners', 'WebsiteController@getPartners');
Route::get('/get-careers', 'WebsiteController@getCareers');
Route::get('/get-career-details/{slug}', 'WebsiteController@getCareerDetails');


Route::get( '/{vue_route?}', 'WebsiteController@home' )->where( 'vue_route', '(.*)' );

resources/views/admin/about_edit.blade.php
@extends('admin.master')

@section('title')
    Mediusware | About Edit | {!! $about->title !!}
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">About Edit | {!! $about->title !!}</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('about.index') !!}">Abouts</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <!-- End Bread crumb and right sidebar toggle -->

    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="card-title">About Update</h4>
                            </div>
                            <div class="col-2 text-right">
                                <a href="{!! url('mediuswareadmin/about') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('about.update', $about->id) !!}" novalidate enctype="multipart/form-data">
                            @method('PATCH')
                            @csrf
                            <div class="row">

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Title<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="title" value="{!! old('title', $about->title) !!}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                            @if ($errors->has('title'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('title') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Description<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">{!! old('description', $about->description) !!}</textarea>
                                            @if ($errors->has('description'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Image<span class="text-danger">*</span> (500x600)</h5>
                                        <div class="controls">
                                            <input type="file" name="image" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}">
                                            <br>
                                            <img src="{!! asset('media/about/'. $about->image) !!}" width="100">
                                            @if ($errors->has('image'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('image') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-7">
                                    <div class="form-group validate">
                                        <h5>Status <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" name="status" {!! $about->status == 'active' ? 'checked':'' !!} value="active" required="" id="status1" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status1">Active</label>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio"  name="status" {!! $about->status == 'inactive' ? 'checked':'' !!} value="inactive" id="status" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status">Inactive</label>
                                                </div>
                                            </fieldset>
                                            @if ($errors->has('status'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('status') }}</strong>
                                                </span>
                                            @endif
                                            <div class="help-block"></div>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            </div>


                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Update</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection
@section('page_js')

@endsection

resources/views/admin/career_view.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Career View
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Career View</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('careers.index') !!}">Career</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="card-title text-info">{{ $career->title }}</h4>
                            </div>
                            <div class="col-2 text-right">
                                <a href="{!! route('careers.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <h4 class="text-info">Vacancy:</h4>
                                <p class="text-justify">{{ $career->vacancy }}</p>

                                <h4 class="text-info">Job Context:</h4>
                                <p class="text-justify">{!! $career->job_context !!}</p>

                                <h4 class="text-info">Job Responsibilities:</h4>
                                <p class="text-justify">{!! $career->job_responsibilities !!}</p>

                                <h4 class="text-info">Employment Status:</h4>
                                <p class="text-justify">{{ $career->employment_status }}</p>

                                <h4 class="text-info">Experience Requirements:</h4>
                                <p class="text-justify">{{ $career->experience_requirements }}</p>

                                <h4 class="text-info">Additional Requirements:</h4>
                                <p class="text-justify">{!! $career->additional_requirements !!}</p>

                                <h4 class="text-info">Compensation & Other Benefits:</h4>
                                <p class="text-justify">{!! $career->other_benefits !!}</p>

                                <h4 class="text-info">Salary:</h4>
                                <p class="text-justify">{{ $career->salary }}</p>

                                <h4 class="text-info">Deadline:</h4>
                                <p class="text-justify">{{ date('d M Y', strtotime($career->deadline)) }}</p>

                                <h4 class="text-info">Read Before Apply:</h4>
                                <p class="text-justify">{!! $career->read_before_apply !!}</p>


                            @if($career->image)
                                <h4 class="text-info">Image:</h4>
                                    <img src="{{ asset('media/career/'. $career->image) }}">
                                @endif
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection

@section('page_js')

@endsection

resources/views/admin/category_edit.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Category Edit | {!! $category->title !!}
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">category Edit | {!! $category->title !!}</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/home') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('category.index') !!}">Categories</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Edit</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>

    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-10">
                                <h4 class="card-title">Category Update</h4>
                            </div>
                            <div class="col-2 text-right">
                                <a href="{!! route('category.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! route('category.update', $category->id) !!}" novalidate>
                            @method('PATCH')
                            @csrf
                            <div class="row">
                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Title<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="title" value="{!! old('title', $category->title) !!}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                            @if ($errors->has('title'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('title') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Short Description</h5>
                                        <div class="controls">
                                            <textarea  name="description" rows="3" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">{!! old('description', $category->description) !!}</textarea>
                                            @if ($errors->has('description'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('description') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-7">
                                    <div class="form-group validate">
                                        <h5>Status <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" name="status" value="active" {!! $category->status == 'active' ? 'checked':''  !!} required="" id="status1" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status1">Active</label>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio"  name="status" value="inactive" {!! $category->status == 'inactive' ? 'checked':''  !!} id="status" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status">Inactive</label>
                                                </div>
                                            </fieldset>
                                            @if ($errors->has('status'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('status') }}</strong>
                                                </span>
                                            @endif
                                            <div class="help-block"></div>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            </div>


                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Update</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection
@section('page_js')

@endsection

resources/views/admin/client_create.blade.php
@extends('admin.master')

@section('title')
    Mediusware | Client Create
@endsection

@section('content')
    <!-- Bread crumb and right sidebar toggle -->
    <div class="page-breadcrumb border-bottom">
        <div class="row">
            <div class="col-lg-3 col-md-4 col-xs-12 align-self-center">
                <h5 class="font-medium text-uppercase mb-0">Client Create</h5>
            </div>
            <div class="col-lg-9 col-md-8 col-xs-12 align-self-center">

                <nav aria-label="breadcrumb" class="mt-2 float-md-right float-left">
                    <ol class="breadcrumb mb-0 justify-content-end p-0">
                        <li class="breadcrumb-item"><a href="{!! url('/') !!}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('home') !!}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('client.index') !!}">Client</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Create</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Bread crumb and right sidebar toggle -->


    <!-- Container fluid  -->

    <div class="page-content container-fluid">

        @include('admin.include.alert')

        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-10 col-sm-8">
                                <h4 class="card-title">Client Create</h4>
                            </div>
                            <div class="col-md-2 col-sm-4 text-right">
                                <a href="{!! route('about.index') !!}" class="btn btn-success"><i class="fa fa-arrow-left"></i> Back</a>
                            </div>
                            <div class="col-12">
                                <hr>
                            </div>
                        </div>

                        <form class="" method="post" action="{!! url('mediuswareadmin/client') !!}" novalidate enctype="multipart/form-data">
                            @csrf
                            <div class="row">

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Title<span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <input type="text" name="title" value="{!! old('title') !!}" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                            @if ($errors->has('title'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('title') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-7 col-md-7 col-xs-12">
                                    <div class="form-group">
                                        <h5>Image<span class="text-danger">*</span> (80x30)</h5>
                                        <div class="controls">
                                            <input type="file" name="image" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" required data-validation-required-message="This field is required">
                                            @if ($errors->has('image'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('image') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-7">
                                    <div class="form-group validate">
                                        <h5>Status <span class="text-danger">*</span></h5>
                                        <div class="controls">
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio" name="status" value="active" required="" id="status1" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status1">Active</label>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="custom-control custom-radio">
                                                    <input type="radio"  name="status" value="inactive" id="status" class="custom-control-input" aria-invalid="false">
                                                    <label class="custom-control-label" for="status">Inactive</label>
                                                </div>
                                            </fieldset>
                                            @if ($errors->has('status'))
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $errors->first('status') }}</strong>
                                                </span>
                                            @endif
                                            <div class="help-block"></div>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            </div>


                            <div class="text-xs-right">
                                <button type="submit" class="btn btn-info">Submit</button>
                                <button type="reset" class="btn btn-inverse">Reset</button>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </div>

        <!-- First Cards Row  -->
    </div>


@endsection

@section('page_js')

@endsection