routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/login', 'Auth\LoginController@login');
Auth::routes();

//Admin Route
Route::group(['prefix' => 'mediuswareadmin', 'middleware' => 'auth'], function(){
    Route::get('dashboard', 'Admin\DashboardController@index')->name('home');
    //services
    Route::resource('services', 'Admin\ServicesController');
    Route::post('service/sortable', 'Admin\ServicesController@sortable');
    //category
    Route::resource('category', 'Admin\CategoryController');
    //portfolio
    Route::resource('portfolio', 'Admin\PortfolioController');
    Route::post('portfolio/sortable', 'Admin\PortfolioController@sortable');
    Route::get('portfolio/image/{id}/delete', 'Admin\PortfolioController@portfolioImageDelete');
    //team
    Route::resource('team', 'Admin\TeamController');
    Route::post('team/sortable', 'Admin\TeamController@sortable');
    //slider
    Route::resource('slider', 'Admin\SliderController');
    Route::post('slider/sortable', 'Admin\SliderController@sortable');
    //feature
    Route::resource('feature', 'Admin\FeatureController');
    //setting
    Route::get('setting', 'Admin\DashboardController@setting');
    Route::post('setting/store', 'Admin\DashboardController@settingStore');
    //career
    Route::resource('careers', 'Admin\CareerController');
    //contact
    Route::get('contacts', 'Admin\DashboardController@contacts');
    Route::get('contact/delete/{id}', 'Admin\DashboardController@contactDelete');
    //about
    Route::resource('about', 'Admin\AboutController');
    Route::post('about/sortable', 'Admin\AboutController@sortable');
    //technology
    Route::resource('technology', 'Admin\TechnologyController');
    Route::post('technology/sortable', 'Admin\TechnologyController@sortable');
    //client
    Route::resource('client', 'Admin\ClientController');
    Route::post('client/sortable', 'Admin\ClientController@sortable');
    //client
    Route::resource('partner', 'Admin\PartnerController');
    Route::post('partner/sortable', 'Admin\PartnerController@sortable');
    //informative
    Route::resource('informative-text', 'Admin\InformativeTextController');
    //informative
    Route::resource('testimonial', 'Admin\TestimonialController');


    Route::group(['middleware' => 'admin'], function(){
        //user
        Route::resource('user', 'Admin\UserController');
        Route::post('user/sortable', 'Admin\UserController@sortable');
    });

});

//Frontend Route
Route::get('/get-abouts', 'WebsiteController@getAbouts');
Route::get('/get-portfolios-showcase', 'WebsiteController@getPortfolioShowcase');
Route::get('/get-portfolios', 'WebsiteController@getPortfolios');
Route::get('/get-portfolios/{slug}', 'WebsiteController@getPortfolios');
Route::get('/get-portfolio-details/{slug}', 'WebsiteController@getPortfolioDetails');
Route::get('/get-categories', 'WebsiteController@getCategories');
Route::get('/get-features', 'WebsiteController@getFeatures');
Route::get('/get-feature-details/{slug}', 'WebsiteController@getFeatureDetails');
Route::get('/get-services', 'WebsiteController@getServices');
Route::get('/get-service-details/{slug}', 'WebsiteController@getServiceDetails');
Route::get('/get-setting', 'WebsiteController@getSettingInfo');
Route::get('/get-teams', 'WebsiteController@getTeam');
Route::get('/get-team-details/{slug}', 'WebsiteController@getTeamDetails');
Route::post('/contact-store', 'WebsiteController@contactStore');
Route::post('/team-contact-store', 'WebsiteController@teamContactStore');
Route::post('/newsletter-store', 'WebsiteController@newsletterStore');
Route::get('/get-technology', 'WebsiteController@getTechnology');
Route::get('/get-clients', 'WebsiteController@getClients');
Route::get('/get-sliders', 'WebsiteController@getSliders');
Route::get('/get-informative-text', 'WebsiteController@getInformativeText');
Route::get('/get-testimonials', 'WebsiteController@getTestimonials');
Route::get('/get-partners', 'WebsiteController@getPartners');
Route::get('/get-careers', 'WebsiteController@getCareers');
Route::get('/get-career-details/{slug}', 'WebsiteController@getCareerDetails');


Route::get( '/{vue_route?}', 'WebsiteController@home' )->where( 'vue_route', '(.*)' );

resources/views/admin/include/alert.blade.php
@if (session('success'))
    <div class="alert alert-success"> <i class="ti-check"></i>
        <b> {{ session('success') }}</b>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    </div>
@elseif(session('error'))
    <div class="alert alert-danger"> <i class="ti-close"></i>
        <b> {{ session('error') }}</b>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">×</span> </button>
    </div>
@endif

resources/views/admin/include/footer.blade.php
<footer class="footer text-center">
    Copyright {!! date('Y') !!} © All Rights Reserved
    <a href="https://mediusware.com">Mediusware</a>
</footer>

resources/views/admin/include/header.blade.php
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header border-right">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
            <a class="navbar-brand" href="{{ url('/mediuswareadmin/dashboard') }}">
                <!-- Logo icon -->
                <b class="logo-icon">
                    <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                    <!-- Dark Logo icon -->
                    <img src="{!! asset('admin') !!}/images/logos/logo-icon.png" alt="homepage" class="dark-logo" />
                    <!-- Light Logo icon -->
                    <img src="{!! asset('admin') !!}/images/logos/logo-light-icon.png" alt="homepage" class="light-logo" />
                </b>
                <!--End Logo icon -->
                <!-- Logo text -->
                <span class="logo-text">
                             <!-- dark Logo text -->
                             <img src="{!! asset('admin') !!}/images/logos/logo-text.png" alt="homepage" class="dark-logo" />
                    <!-- Light Logo text -->
                             <img src="{!! asset('admin') !!}/images/logos/logo-light-text.png" class="light-logo" alt="homepage" />
                        </span>
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto">
                <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-18"></i></a></li>
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" id="2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="font-18 mdi mdi-gmail"></i>
                        <div class="notify">
                            <span class="heartbit"></span>
                            <span class="point"></span>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-left mailbox animated bounceInDown" aria-labelledby="2">
                        <ul class="list-style-none">
                            <li>
                                <div class="drop-title border-bottom">You have 4 new messanges</div>
                            </li>
                            <li>
                                <div class="message-center message-body">
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="message-item">
                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/1.jpg" alt="user" class="rounded-circle"> <span class="profile-status online pull-right"></span> </span>
                                        <span class="mail-contnet">
                                                    <h5 class="message-title">Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:30 AM</span> </span>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="message-item">
                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/2.jpg" alt="user" class="rounded-circle"> <span class="profile-status busy pull-right"></span> </span>
                                        <span class="mail-contnet">
                                                    <h5 class="message-title">Sonu Nigam</h5> <span class="mail-desc">I've sung a song! See you at</span> <span class="time">9:10 AM</span> </span>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="message-item">
                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/3.jpg" alt="user" class="rounded-circle"> <span class="profile-status away pull-right"></span> </span>
                                        <span class="mail-contnet">
                                                    <h5 class="message-title">Arijit Sinh</h5> <span class="mail-desc">I am a singer!</span> <span class="time">9:08 AM</span> </span>
                                    </a>
                                    <!-- Message -->
                                    <a href="javascript:void(0)" class="message-item">
                                        <span class="user-img"> <img src="{!! asset('admin') !!}/images/users/4.jpg" alt="user" class="rounded-circle"> <span class="profile-status offline pull-right"></span> </span>
                                        <span class="mail-contnet">
                                                    <h5 class="message-title">Pavan kumar</h5> <span class="mail-desc">Just see the my admin!</span> <span class="time">9:02 AM</span> </span>
                                    </a>
                                </div>
                            </li>
                            <li>
                                <a class="nav-link text-center link text-dark" href="javascript:void(0);"> <b>See all Notifications</b> <i class="fa fa-angle-right"></i> </a>
                            </li>
                        </ul>
                    </div>
                </li>

            </ul>

            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                <li class="nav-item search-box">
                    <form class="app-search d-none d-lg-block">
                        <input type="text" class="form-control" placeholder="Search...">
                        <a href="#" class="active"><i class="fa fa-search"></i></a>
                    </form>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle waves-effect waves-dark" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="{!! asset('admin') !!}/images/users/1.jpg" alt="user" class="rounded-circle" width="36">
                        <span class="ml-2 font-medium">{!! Auth::user()->name !!}</span><span class="fas fa-angle-down ml-2"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                        <div class="d-flex no-block align-items-center p-3 mb-2 border-bottom">
                            <div class=""><img src="{!! asset('admin') !!}/images/users/1.jpg" alt="user" class="rounded" width="80"></div>
                            <div class="ml-2">
                                <h4 class="mb-0">{!! Auth::user()->name !!}</h4>
                                <p class=" mb-0 text-muted">{!! Auth::user()->email !!}</p>
                                <a href="javascript:void(0)" class="btn btn-sm btn-danger text-white mt-2 btn-rounded">View Profile</a>
                            </div>
                        </div>

                        <a class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" href="javascript:void(0)">
                            <i class="fa fa-power-off mr-1 ml-1"></i> Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/include/navbar.blade.php
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                    <a class="sidebar-link has-arrow waves-effect waves-dark profile-dd" href="javascript:void(0)" aria-expanded="false">
                        <img src="{!! asset('admin') !!}/images/users/1.jpg" class="rounded-circle ml-2" width="30">
                        <span class="hide-menu">{!! Auth::user()->name !!} </span>
                    </a>
                    <ul aria-expanded="false" class="collapse  first-level">
                        <li class="sidebar-item">
                            <a href="javascript:void(0)" class="sidebar-link">
                                <i class="ti-user"></i>
                                <span class="hide-menu"> My Profile </span>
                            </a>
                        </li>

                        <li class="sidebar-item">
                            <a href="javascript:void(0)" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" href="javascript:void(0)" class="sidebar-link">
                                <i class="fas fa-power-off"></i>
                                <span class="hide-menu"> Logout </span>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>

                <li class="sidebar-item">
                    <a href="{!! route('home') !!}" class="sidebar-link">
                        <i class="mdi mdi-view-dashboard"></i>
                        <span class="hide-menu"> Dashboard </span>
                    </a>
                </li>
                <div class="devider"></div>

                @if(Auth::user()->role == 'admin')
                <li class="sidebar-item {!! Request::is('mediuswareadmin/user*') ? 'selected':'' !!}">
                    <a href="{!! route('user.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/user*') ? 'active':'' !!}">
                        <i class="fa fa-users"></i>
                        <span class="hide-menu"> User </span>
                    </a>
                </li>
                @endif

                <li class="sidebar-item {!! Request::is('mediuswareadmin/service*') ? 'selected':'' !!}">
                    <a href="{!! route('services.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/service*') ? 'active':'' !!}">
                        <i class="mdi mdi-server-network"></i>
                        <span class="hide-menu"> Services </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/categor*') ? 'selected':'' !!}">
                    <a href="{!! route('category.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/categor*') ? 'active':'' !!}">
                        <i class="mdi mdi-cube"></i>
                        <span class="hide-menu"> Categories </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/portfolio*') ? 'selected':'' !!}">
                    <a href="{!! route('portfolio.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/portfolio*') ? 'active':'' !!}">
                        <i class="mdi mdi-code-brackets"></i>
                        <span class="hide-menu"> Portfolios </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/team*') ? 'selected':'' !!}">
                    <a href="{!! route('team.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/team*') ? 'active':'' !!}">
                        <i class="fa fa-users"></i>
                        <span class="hide-menu"> Teams </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/slider*') ? 'selected':'' !!}">
                    <a href="{!! route('slider.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/slider*') ? 'active':'' !!}">
                        <i class="fa fa-sliders-h"></i>
                        <span class="hide-menu"> Sliders </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/about*') ? 'selected':'' !!}">
                    <a href="{!! route('about.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/about*') ? 'active':'' !!}">
                        <i class="fa fa-calendar-plus"></i>
                        <span class="hide-menu"> About </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/technology*') ? 'selected':'' !!}">
                    <a href="{!! route('technology.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/technology*') ? 'active':'' !!}">
                        <i class="fa fa-signal"></i>
                        <span class="hide-menu"> Technology </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/client*') ? 'selected':'' !!}">
                    <a href="{!! route('client.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/client*') ? 'active':'' !!}">
                        <i class="fa fa-user-secret"></i>
                        <span class="hide-menu"> Clients </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/partner*') ? 'selected':'' !!}">
                    <a href="{!! url('mediuswareadmin/partner') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/partner*') ? 'active':'' !!}">
                        <i class="fa fa-handshake"></i>
                        <span class="hide-menu"> Partners </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/feature*') ? 'selected':'' !!}">
                    <a href="{!! route('feature.index') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/feature*') ? 'active':'' !!}">
                        <i class="fa fa-file-archive"></i>
                        <span class="hide-menu"> Features </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/contact*') ? 'selected':'' !!}">
                    <a href="{!! url('mediuswareadmin/contacts') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/contact*') ? 'active':'' !!}">
                        <i class="mdi mdi-mailbox"></i>
                        <span class="hide-menu"> Contacts </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/informative-text*') ? 'selected':'' !!}">
                    <a href="{!! url('mediuswareadmin/informative-text') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/informative-text*') ? 'active':'' !!}">
                        <i class="mdi mdi-information"></i>
                        <span class="hide-menu"> Informative Text </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/testimonial*') ? 'selected':'' !!}">
                    <a href="{!! url('mediuswareadmin/testimonial') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/testimonial*') ? 'active':'' !!}">
                        <i class="fa fa-info"></i>
                        <span class="hide-menu"> Testimonial </span>
                    </a>
                </li>

                <li class="sidebar-item {!! Request::is('mediuswareadmin/setting*') ? 'selected':'' !!}">
                    <a href="{!! url('mediuswareadmin/setting') !!}" class="sidebar-link {!! Request::is('mediuswareadmin/setting*') ? 'active':'' !!}">
                        <i class="mdi mdi-settings"></i>
                        <span class="hide-menu"> Setting </span>
                    </a>
                </li>
                <li class="sidebar-item {!! Request::is('mediuswareadmin/career*') ? 'selected':'' !!}">
                    <a href="{{ route('careers.index') }}" class="sidebar-link {!! Request::is('mediuswareadmin/career*') ? 'active':'' !!}">
                        <i class="mdi mdi-blur-radial"></i>
                        <span class="hide-menu"> career </span>
                    </a>
                </li>


{{--                <li class="sidebar-item">--}}
{{--                    <a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">--}}
{{--                        <i class="mdi mdi-cart-outline"></i>--}}
{{--                        <span class="hide-menu">Portfolios</span>--}}
{{--                    </a>--}}
{{--                    <ul aria-expanded="false" class="collapse first-level">--}}
{{--                        <li class="sidebar-item">--}}
{{--                            <a href="eco-products.html" class="sidebar-link">--}}
{{--                                <i class="mdi mdi-cards-variant"></i>--}}
{{--                                <span class="hide-menu">Categories</span>--}}
{{--                            </a>--}}
{{--                        </li>--}}
{{--                        <li class="sidebar-item">--}}
{{--                            <a href="eco-products-cart.html" class="sidebar-link">--}}
{{--                                <i class="mdi mdi-cart"></i>--}}
{{--                                <span class="hide-menu">Portfolios</span>--}}
{{--                            </a>--}}
{{--                        </li>--}}
{{--                        --}}
{{--                    </ul>--}}
{{--                </li>--}}

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>